# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with: 
         node-version: 12
         
      - name: Install Deps
        run: npm install
         
      - name: Build React App                              
        run: CI=false npm run build

      - name: Install surge globally
        run: npm install --global surge
        
      - name: Deploy to surge
        run: surge ./build resto-app-tailwind-yudhistiroagung.surge.sh --token ${{secrets.SURGE_TOKEN}}
        
      
